language: bash
env:
  matrix:
  - OS=debian DIST=jessie ARCH=armel
  - OS=debian DIST=jessie ARCH=armhf
  - OS=raspbian DIST=jessie ARCH=armhf
  global:
  - DEBOOTSTRAP=qemu-debootstrap
  - DEPLOY_HOST=ev3dev-docker-docker.bintray.io
  - secure: WXDPxJmIil5Cr0+LW4jlNmOFCx1Xk37XQICX5AA11A3Z6EuUWQWrWwQ4jToSYyUrkM6035TMXECLQ15x+Q1FjUXQWVTPc5QmFtXHw0sR7Npn37LIZrdWfZsZYc8cf1nhX9HLx3amMZBGv74Rn/+/JtZ8WpH5tj2Nb8A6Tm3oHeAfXMqApjTZJ9QYl0i0S++acG+j1QDlj4DXl289N2MKrUNWupjxfyOgaV4qedmXQdlrfcKEqREZKXgcLDh86L5P3Xel6IBuS/sYqylNvTCr/9D0R9BQqNa8tHNJAKUdBRhM6Fbdl8+U+srSqanNLgX8F8vSYM4nFCoyBLvh+pVtyaFnbKth6hkiSYQIZVwL4gsGfEzT0MJgZ8wicgdEdwkWe/AbS68FxXioK4wwCgUi+Ohbm7HweYi5sWU6Ldgai2SiQ/fC1+Le3bwHYyYM7bS+OHsHuLRLKiwHqXWJs8PJTkuTChNAPmpK2kLUR39exMpYJHXqLfQaVD03ZypWUGGPS8bQoZFnyGOqGvcBZeQcs1e3it/AVyW+WmSuASNP406QoH2KdfXR7SGYHDSrMf8bjHnvE4HtGc8POTQIVSkEDQZ3H7ENv/lyTIiJCXQi4mDrwe0LuW0bl8wPEeYU6P1tQ2sUl8ovOTnOknmIQVZbTRphW0ZU3SFVfzMD8V+IW6Y=
  - secure: EqZXhdLDg1IvqOtE3Eo+tp0Oc5ndQlFXLTprxjm78R8gOtgicT5nnwHXJTNH2SMhy/UDyWUJV59JjT44T/c3D7JeKvwWQ0Hzuqjp71dV1TQcCEmj1Yw1Jj6h4ofypt2li6ziTpSw2lGnJQzFShGO2fpR7kfsUNVX5WleUZlBE+3skqV46qhySIPES/0/oJY5UjOd/SNAksUSSaIIKwVGUEOxVH3lz2YtOFtC/QqyuHm9zE9AXO1YVSdfJ88jDIxAndWloB/kcAe50SXkUk4wO9NtSD3swC+2QDTAcGXJa6hL1PUquB8TeHn0Z7jsXMkd74ELc9w9YNvRZye5Rg6DYiho5a1F5zURQijlIlGBhFm1PiL05SrgG6N8biWXmslBXAFmFrYeWruR2b82pO13od/E/sclcMhzlScL1W9H2NZ+rSOSH2VBleQNg7lLMZc8dxP+cm2YmSOYXr5vyvJxlrx5kY87Je5+Z6hGoSY1n+TkearjcETj8LDMO+1uvFrCLAYhZAz1xg63lPyEkGh/UEGWV3jjS3t+U/cOrSU64nh3L1AbuvlVwQcAbdLai2F8w1TDiGdcW2TWOhe0IrY3rl1DI1mfvbcRIYu23wjVXeoqetML0QziSVkKwJG7uSXvtcNFn8VwTrtSE2nE/l/vGOjB/vgbkWBh1DwwSL0bSp4=
sudo: required
dist: trusty
services: docker
install:
- >
  sudo apt-get update -y && sudo apt-get install -y
  debian-archive-keyring
  qemu-user-static
- if [ "$OS" == "raspbian" ]; then
   wget --directory-prefix=/tmp http://archive.raspbian.org/raspbian/pool/main/r/raspbian-archive-keyring/raspbian-archive-keyring_20120528.2_all.deb;
   sudo dpkg -i /tmp/raspbian-archive-keyring_20120528.2_all.deb;
   export MIRROR=http://archive.raspbian.org/raspbian;
  fi
before_script:
- docker --version
- export IMAGE=$OS-$DIST-$ARCH
script:
- >
  sudo -E /usr/share/docker-engine/contrib/mkimage.sh
  -t $IMAGE
  debootstrap
  --keyring=/usr/share/keyrings/$OS-archive-keyring.gpg
  --arch=$ARCH
  --variant=minbase
  $DIST
  $MIRROR
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    export TAG=$(docker run -i -t $IMAGE cat /etc/debian_version | tr -d '\r\n');
    docker tag $IMAGE $DEPLOY_HOST/$IMAGE;
    docker tag $IMAGE $DEPLOY_HOST/$IMAGE:$TAG;
    docker login -u dlech -p $API_KEY -e $EMAIL $DEPLOY_HOST;
    docker push $DEPLOY_HOST/$IMAGE;
    docker push $DEPLOY_HOST/$IMAGE:$TAG;
  fi
