language: bash
env:
  matrix:
  - OS=debian DIST=jessie ARCH=armel
  - OS=debian DIST=jessie ARCH=armhf
  - OS=raspbian DIST=jessie ARCH=armhf
  - OS=debian DIST=stretch ARCH=armel
  - OS=debian DIST=stretch ARCH=armhf
  - OS=raspbian DIST=stretch ARCH=armhf
  global:
  - DEBOOTSTRAP=qemu-debootstrap
  - NAMESPACE=ev3dev
  - secure: iSixWxcGG+BLi0XmkQ3b+4ZQhpPZsEvFdBsorjVG1hnZW26si0OVq9C5fC1HnR6sGvZ7bJPfHlT4FsIwrnF2gPrEvlcHhjsoqLfWSt8sEZjpEx/Pd/IwjnSTG8hr5DUO8/gjKrwIKTd+NAiVu/P8HBC9Z5trhvHBNsjscOF3trX5pIYD/NrAOxqQPswREL2Oj0hfkVGIDeW+ctsN8yO76Gm5qeyyoPyQLl93pBWBfnoHcPxr5KXjTR6XmStkpKW9ApGG0AD3g4JwxyE7HpaWwknnwVDeyp2h8sE2Ozv1AEKXtesFCFCLHnzqpGXuG8FOxynA5T1RVRV6BX0YMPW138yo7mjdoUTJUB83uiN9/BNRSYZNuPVu+myp1bz8RsqLeF/sSU/k8dZkg7Dw43bb2TCaNg8G7FCytpUH9aidJDhf6b+i2Bc7k36Limo5iaa35eULtc9MANi7cx85VLrQjOgrnROKNAljpc6bGhKH8V73pWpZsjOVt9ifVQhd/ABv6/uEHus6a4mhIcIompqBMuUxpZcNbrI4ADHD4XUwVvy0Mqai/U7T8ermMIGYyilXZlTlpCwC7xtDAksivVMUGocACuOVUqcylQKJWnA+7lm4/Ck2ot29hWHMszrR7vi8jhJm3I2XQiuPqwDZSA2JGWpQ6Iqq7o1mwTX15EIdXZs=
  - secure: l8cWUA5/SJf9s6v9XJTHsTT1M0jOsd4ThuZMQKIHoVZvLrklF72f5jSpj4+vEvb3rB+qDL0r01D7H4DEUPtAfXJb5WTEMO400DRFdq2nnn/tV5CSSO3m6HsXPnMQJga9VJBiSeVVWVUN8I5qS5m8851Q6GYqMnKsmvlizfK4sCCv0+n8/ESUUgvahFhQ5nQdsUt9nolZyR2q35BLOC1sFGOoRcdJG7TsdvoFWJgPQatz3+o0UhQadP+JXgBPZIH5bjGk7KjnKUalEvsQAxTtoA+o67uCQXDUu8rnpHmw3Rx/U41mwriSjaKQJYrnPGj28YIE4xqdsyDA5rcbu/Hpj3vJXSToTMF5K2KYsDSAfVxhHw+Xoae7958DIOgObAhm2qg1CzUhaF+8DObrT+r525O+6KlHyFQ02kpzo6QWJu4cxe02/s6L3vmtTCaYgdKkQkzYl2MgibPf7wW/5Kg2UrTGagPjPNs7p42MOmQa5xCp3ov7nSdXedMmu7mx+Y37yY0T8DyTdHGjsxOGz3YhkvdbF3iDBRABSHl6l0FNR5ApiGAmH4OZnoNFpCUcZHeIrdbiKL+zgelgNwgqZYlPbNrsaDXx1pa6Vfyg4c2CBIdPZkf1a3tfW0vTvpKjKkVkkNPrgtXEBmWxlaWFCu7Akn8DY5LtndgGemVTGZjZ9SA=
sudo: required
dist: trusty
services: docker
install:
- >
  sudo apt-get update -y && sudo apt-get install -y
  debian-archive-keyring
  debootstrap
- wget http://mirrors.kernel.org/ubuntu/pool/universe/q/qemu/qemu-user-static_2.8+dfsg-3ubuntu2_amd64.deb &&
  sudo dpkg -i qemu-user-static_2.8+dfsg-3ubuntu2_amd64.deb
- if [ "$OS" == "raspbian" ]; then
   wget --directory-prefix=/tmp http://archive.raspbian.org/raspbian/pool/main/r/raspbian-archive-keyring/raspbian-archive-keyring_20120528.2_all.deb;
   sudo dpkg -i /tmp/raspbian-archive-keyring_20120528.2_all.deb;
   export MIRROR=http://archive.raspbian.org/raspbian;
  fi
before_script:
- docker --version
- export IMAGE=$OS-$DIST-$ARCH-qemu-minbase
- if [ ! -e /usr/share/debootstrap/scripts/stretch ]; then
      sudo ln -s /usr/share/debootstrap/scripts/sid /usr/share/debootstrap/scripts/stretch;
  fi
script:
- >
  sudo -E /usr/share/docker-engine/contrib/mkimage.sh
  -t $IMAGE
  debootstrap
  --keyring=/usr/share/keyrings/$OS-archive-keyring.gpg
  --arch=$ARCH
  --variant=minbase
  $DIST
  $MIRROR
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    export VERSION_TAG=$(docker run -i -t $IMAGE cat /etc/debian_version | tr -d '\r\n');
    docker tag $IMAGE $NAMESPACE/$IMAGE;
    docker tag $IMAGE $NAMESPACE/$IMAGE:$VERSION_TAG;
    docker login --username $DOCKER_USER --password $DOCKER_PASSWORD;
    docker push $NAMESPACE/$IMAGE;
    docker push $NAMESPACE/$IMAGE:$VERSION_TAG;
  fi
